### ISSUE TITLE
dynamic websocket routes

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [fastify/fastify-websocket#102]
hi, 

I need to generate new websocket routes after a post request, yet the client that tries to connect to it will get a 500 error. 
I tried to put the route in beforehand, which worked well, but trying to create it on the fly, won't do. Should I be better using the ws package for this?
```

        const createWebsocketRoute = (listenKey) => {

            console.log('?CREATE?')

            // CRASHES HERE.

            fastify.get(`/ws/x`, { websocket: true }, ({socket}, res) => { // needs to close previous socket
                
                console.log('socket connected:', listenKey)
    
                setTimeout(() => {
    
                    socket.send(JSON.stringify({
                        d: "100.00000000",
                        T: 1573200697068,
                        E: 1573200697110,
                    }))
                    
                }, 500)
            })
        }


        fastify.route({ method: 'POST', websocket: false, url: '/api/v3/userDataStream', handler: async ({query}, res) => {

            listenKey = crypto.createHash('sha256').update(crypto.randomBytes(256)).digest("hex").slice(0, 64)

             console.log('new listenKey:', listenKey)

             createWebsocketRoute(listenKey)

            // CLIENT CRASHES

            await new Promise(rs => setTimeout(rs, 1000)) // tried to add some timeout for maybe the route has to start up=? 
            res.send({listenKey})

        }})

```

**Comment by mcollina** [comment]
dynamically defining routes is likely to lead to memory leaks, and therefore is not supported.

**Comment by airhorns** [comment]
Fastify works best if you define all your routes up front which you can do using parameters in the route template, like 

```
fastify.get(`/ws/:userID`, { websocket: true }, () => {})
```

 If you declare that route once at the top level then all requests with that pattern will hit that route handler. If you need to authenticate that route, you can use normal session plugins like `fastify-secure-session` and a `preValidate` handler, or you could use something like JWT tokens that you pass to the user like you are doing with the listen key. Creating new routes at runtime is gonna be slow and suck up a lot of memory and so it is unsupported in fastify, see https://github.com/fastify/fastify/issues/1771.

**Comment by hp8wvvvgnj6asjm7** [comment]
> 
> 
> Fastify works best if you define all your routes up front which you can do using parameters in the route template, like
> 
> ```
> fastify.get(`/ws/:userID`, { websocket: true }, () => {})
> ```
> 
> If you declare that route once at the top level then all requests with that pattern will hit that route handler. If you need to authenticate that route, you can use normal session plugins like `fastify-secure-session` and a `preValidate` handler, or you could use something like JWT tokens that you pass to the user like you are doing with the listen key. Creating new routes at runtime is gonna be slow and suck up a lot of memory and so it is unsupported in fastify, see [fastify/fastify#1771](https://github.com/fastify/fastify/issues/1771).

thanks! thats what i was looking for.
