### ISSUE TITLE
Simple example of usage?

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify-websocket#11]
Hello everyone!
I need a simple example of this plugin to integrate to my chat application.

Can someone help me?
Thanks!

**Comment by blacksmoke26** [comment]
Damn, I am also looking for that! Pretty please.... or at-least Socket.IO Support!

**Comment by lgertel** [comment]
@mcollina possible to use socket in fastify ecosistem right? If not, there are important concerns to integrate as a plugin?

**Comment by delvedor** [comment]
This plugin is very low level, if you want something easier/high level you can use [`fastify-ws`](https://github.com/gj/fastify-ws).

**Comment by lgertel** [comment]
@delvedor dude this is awesome. I'll take a look and maybe later spend some time on this one.
