### ISSUE TITLE
`verifyClient` isn't working and support should likely be removed

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [fastify/fastify-websocket#182]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.x.x

### Node.js version

unknown

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

unknown

### Description

When I tried using `verifyClient` in my server, Fastify kept sending `Reply already sent` errors. And in the `ws` documentation, it literally encourages _not_ to use it. I believe this plugin should throw an error or deprecation warning when attempting to use `verifyClient` to avoid these issues in the future.

### Steps to Reproduce

Start a Fastify server using this plugin with a `verifyClient` option and logging on.

### Expected Behavior

_I believe this plugin should throw an error or deprecation warning when attempting to use `verifyClient` to avoid these issues in the future._

**Comment by mcollina** [comment]
I think we should just remove it from our docs. I don't think we are doing any specific about it as it's an option of ws. Adding a deprecation here will only increase the maintenance work.

**Comment by darkgl0w** [comment]
Strange. I have no issue with verifyClient.
Can you provide a reproducible example where it fails ?

**Comment by a-a-GiTHuB-a-a** [comment]
It's weird, but in `hChat`, when I used it, I got the error.
Sadly, I don't have a way to show the code...

**Comment by Eomm** [comment]
> And in the ws documentation, it literally encourages not to use it

I think it should be the `ws` module to emit the waning if they discourage its usage

**Comment by darkgl0w** [comment]
A little working example, that makes use of the `verifyClient` option :

#### Server side :
- initialize a project 
```sh
mkdir fastify-ws-example && cd fastify-ws-example && touch index.js && npm init --yes
```
- install ` fastify` and `fastify-websocket`
```sh
npm i fastify fastify-websocket
```
- inside `index.js` paste this
```js
'use strict';

const Fastify = require('fastify');
const ws = require('fastify-websocket');

const app = Fastify();
app.register(ws, {
  options: {
    verifyClient: function (info, next) {
      const { url } = info.req;
      const token = new URLSearchParams(url.replace(/^.*\?/, '')).get('token');

      if (!token) {
        console.log({ error: 'unauthorized' })
        next(false, 401, 'Unhautorized');
      } else {
        console.log({ token });
        next(true);
      }
    }
  }
});

app.get('/', { websocket: true }, (connection, request) => {
  connection.socket.on('message', (message) => {
    console.log(`client: ${Buffer.from(message).toString()}`);
    connection.socket.send('hi from server');
  });
});

app.listen({ host: '127.0.0.1', port: 3000 });
```
- run the server with `node index.js`

#### Client side :

Create an html page and paste this :

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <script type="text/javascript">
  const io = new WebSocket(`ws://localhost:3000/?token=hello`);
  // const io = new WebSocket(`ws://localhost:3000`);

  io.onopen = (socket) => {
    console.log('connection');
  };

  io.onmessage = (message) => {
    console.log(message.data);
  };

  io.onclose = () => {
    console.log('disconnected');
  };
  </script>
</body>
</html>
```

Open this html page in your browser and open your browser console (e.g.: `Ctrl + Shift + K` in firefox),
if you connect to the websocket server with
```js
const io = new WebSocket(`ws://localhost:3000/?token=hello`);
```
it will be ok and the server will log `{ token: 'hello' }`, instead if you connect to the websocket server with
```js
const io = new WebSocket(`ws://localhost:3000`);
```
in your browser console you will see a `401 Unauthorized` error and your server will log `{ error: 'unauthorized' }`.

**Comment by a-a-GiTHuB-a-a** [comment]
Strange. At one point in `hChat`, it would throw the error.

**Comment by darkgl0w** [comment]
I will close this issue, `verifyClient` is working as it should and without a proper reproducible example we can not help you more than this.

Feel free to reopen if you are able to provide some code we can look at.
