### ISSUE TITLE
Why do i get "closed incoming websocket connection"

### ISSUE THREAD

**Issue by SKrind0** [fastify/fastify-websocket#202]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Plugin version

5.0.0

### Node.js version

17.8.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

21H2

### Description

when i start my server with fastify and create a connection with 
fastify-websocket i get this message and i don't know why i get it

![image](https://user-images.githubusercontent.com/68449193/168398615-604e9a9a-b937-4b4f-b3cf-dfce5f6ce83a.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/68449193/168398660-75ea821b-1d52-4253-b826-da3d978fef35.png)

### Expected Behavior

So I want someone to help me solve it

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by SKrind0** [comment]
the repository link is here https://github.com/SKrind0/fastifyWebsocket-error/tree/main

**Comment by mcollina** [comment]
based on your code, you need to connect to: 

```js

const ws = new WebSocket(`ws://localhost:3001/ws`);

```

**Comment by SKrind0** [comment]
yes, but when I use postman I get this error: 

![image](https://user-images.githubusercontent.com/68449193/168440266-7cd819d3-2f57-4b16-ab22-a9ac5ba7e51e.png)

that doesn't happen with the simple websocket client extension:

![image](https://user-images.githubusercontent.com/68449193/168440311-a9c01b89-a925-411b-bf28-f50632d4cfff.png)

**Comment by SKrind0** [comment]
sorry i fixed the problem now i have an error with socket-io and the postman sends me an error saying:

![image](https://user-images.githubusercontent.com/68449193/168452492-53018a07-2747-4630-bfcc-f7c91cf15b62.png)

the updated code is at: https://github.com/SKrind0/fastifyWebsocket-error/tree/d0578008f726fd2593ff675a54d2ab2e45c2a40a

**Comment by mcollina** [comment]
For some reason your server is not started or is listening on that port. I think you are on Windows, try to use `127.0.0.1` instead of `localhost`.

**Comment by SKrind0** [comment]
> For some reason your server is not started or is listening on that port. I think you are on Windows, try to use `127.0.0.1` instead of `localhost`.

yes i use windows i will try

**Comment by SKrind0** [comment]
thanks now my problem is socket-io keeps sending me this error: 

![image](https://user-images.githubusercontent.com/68449193/168473944-9dc60851-9d07-4283-ad62-8b4eb475c374.png)

so I make the request:

![image](https://user-images.githubusercontent.com/68449193/168473972-272f6118-3cd0-4fae-bde7-5f7adc6eff7f.png)

**Comment by climba03003** [comment]
> thanks now my problem is socket-io keeps sending me this error:
> 

Why are you connecting a raw websocket server with `socket.io`?
It means that you need to implement the whole `socket.io` server logic yourself.

The error now very clear you do not have a websocket handler for path `/socket.io/`

**Comment by SKrind0** [comment]
ok so how can i use socket-io with fastify?
 I found a plugin for that, but I don't know if it will work, do you think it will work?

link of the plugin: https://github.com/alemagio/fastify-socket.io
