### ISSUE TITLE
When Fastify is listening on IPv4+6, routes return 404 when connecting from IPv6 addresses

### ISSUE THREAD

**Issue by zenoamaro** [fastify/fastify-websocket#207]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.1

### Plugin version

6.0.1

### Node.js version

16.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

When configured to listen on `localhost`, Fastify spawns two `http.Server`s: one on IPv4 address `localhost` on startup, which is exposed as `fastify.server` ([fastify/server.js:15](https://github.com/fastify/fastify/blob/main/lib/server.js#L15)), and a second one on IPv6 address `::`, some time after the first one has finished listening, exposed through symbol `kServerBindings` ([fastify/server.js:133](https://github.com/fastify/fastify/blob/main/lib/server.js#L133)).

However, `fastify-websocket` only listens to `upgrade` events on the first server ([fastify-websocket/index.js:41](https://github.com/fastify/fastify-websocket/blob/master/index.js#L41)), which means connections from IPv6 addresses are never upgraded, and so never handled, and reach the fallback 404 handler.

On my machine, where IPv6 is available, Node `ws` connections have a `remoteAddress` of `127.0.0.1`, and reach the first `http.Server`, triggering the proper `upgrade` handling. However, browser `WebSocket` connections come from `::1`, and reach the second, which has no `upgrade` handler set up. In the following extract from the logs, the only difference in the requests is `remoteAddress`:

~~~json
{"level":30,"time":1655248914754,"pid":86869,"hostname":"<my hostname>","reqId":"req-1","req":{"method":"GET","url":"/connect/worker","hostname":"localhost:3001","remoteAddress":"127.0.0.1","remotePort":55029},"msg":"incoming request"}
☝️ No failure, and my route handler logs successfully afterwards

{"level":30,"time":1655248918573,"pid":86869,"hostname":"<my hostname>","reqId":"req-2","req":{"method":"GET","url":"/connect/worker","hostname":"localhost:3001","remoteAddress":"::1","remotePort":55032},"msg":"incoming request"}
{"level":30,"time":1655248918577,"pid":86869,"hostname":"<my hostname>","reqId":"req-2","res":{"statusCode":404},"responseTime":3.638867139816284,"msg":"request completed"}
☝️ 404 on the same route
~~~

Because the second `http.Server` is only created some time after the first has finished listening, and is still not ready even when the `onReady` hook triggers, a clean fix for this is not obvious, without changing the Fastify API. Additionally, the second server is only exposed through a symbol from an untyped module, which complicates things further.

My current work-around is to forward upgrade events from the second server to the first during the listen callback:

~~~ts
// @ts-ignore untyped module
import symbols from 'fastify/lib/symbols.js';

fastify.listen({port: 3001}, () => {
  // @ts-ignore unknown index access
  fastify[symbols.kServerBindings].forEach((server) => {
    server.on('upgrade', (...args: any[]) => {
      fastify.server.emit('upgrade', ...args);
    });
  });
});
~~~

### Steps to Reproduce

* Set up a simple websocket route
* Listen on `localhost`, with ipv6 enabled, causing a multiple server binding
* Trigger a WebSocket call from `remoteAddress`: `::1`
* → 404

### Expected Behavior

* All connections are handled properly

**Comment by mcollina** [comment]
Good spot! I will take a look as soon as I can (but it might take a few days).

**Comment by mcollina** [comment]
cc @jsumners we did not think about this use case when doing the multiple interface fix.

**Comment by climba03003** [comment]
I think we may consider `pre-close` event. 
It actually affect all the usage with direct attach `server`.
e.g. `socket.io`

**Comment by mcollina** [comment]
If you want to take a stab at this go ahead @climba03003!

**Comment by climba03003** [comment]
> If you want to take a stab at this go ahead @climba03003!

I am thinking of expose a new API `.attachFrom(<function interact with server>, <function execute before close>)` or `.attachFrom({ attach() {}, close() {} })`.
```js
fastify.attachFrom(function(server) {
  server.on('upgrade', function() {})
}, function(server) {
  // clean up here
})

or 

fastify.attachFrom({
  attach(server) {},
  close(server) {}
})
```

**Comment by jsumners** [comment]
> cc @jsumners we did not think about this use case when doing the multiple interface fix.

I genuinely never even think about the websocket module.

**Comment by zenoamaro** [comment]
Perhaps it's possible to proxy `Server` instances, so that method calls and events transparently apply to a list of N servers. It should cover most use-cases correctly, without requiring modifications; but it may be surprising if eg. the code expects `listen` to be triggered only once.

It could also be possible to expose `Fastify::servers` in addition to `Fastify::server` so modules can opt-in. But every module relying on `Fastify::server` will have to be updated.

**Comment by airhorns** [comment]
I take it there is no way to get the one server instance to listen on multiple interfaces eh? Another less-fundamental fix would be to have the fastify instance itself emit the `upgrade` event (isntead of the server), and have it proxy through events from all servers it manages under the hood

**Comment by mcollina** [comment]
> I take it there is no way to get the one server instance to listen on multiple interfaces eh? Another less-fundamental fix would be to have the fastify instance itself emit the upgrade event (isntead of the server), and have it proxy through events from all servers it manages under the hood

This would actually be amazing.

**Comment by pvanagtmaal** [comment]
The other way round is also true. If `localhost` resolves to `::1` first then ipv4 connections result in a 404.

**Comment by mcollina** [comment]
Could you try https://github.com/fastify/fastify/pull/4190 and see if it solves your problem?

**Comment by pvanagtmaal** [comment]
@mcollina Seems to be working fine for both ipv4 and ipv6, confirmed with network traces. 😄 Thanks!

**Comment by zenoamaro** [comment]
Thanks! ❤️
