### ISSUE TITLE
Is it possible to get a socket of a client 

### ISSUE THREAD

**Issue by bacloud22** [fastify/fastify-websocket#210]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Sockets are retrieved from connection object `connection.socket`; then to broadcast a message we iterate over all clients connected to the same endpoint: `fastify.websocketServer.clients`.

What I want to achieve, is to send some message not to all clients, but to some channel and a channel is a list of sockets in my case.

Is this possible ?
Thanks a lot

**Comment by mcollina** [comment]
This functionality is out of scope for this module. However, you can take a look at http://npm.im/mqemitter as you can use it to provide a channel-like abstraction.

**Comment by climba03003** [comment]
> for one client, there might be one or more sockets (open tabs/ session...)

Your assumption is wrong.
`one client means one socket`, there never be multiple `socket` binding the same `client`.

**Comment by bacloud22** [comment]
Yes thanks @climba03003 this is the chosen implementation here.
