### ISSUE TITLE
Delay openning connection

### ISSUE THREAD

**Issue by punkpeye** [fastify/fastify-websocket#221]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have a use case that requires to delay initializing socket connection until some async checks are complete, i.e. client should not receive `open` event until then.

Is it possible to do this using `fastify-websocket` or do I need to go a layer down to using `ws`?

**Comment by mcollina** [comment]
I think you can use a `onRequest` or `preHandler` hook.

**Comment by punkpeye** [comment]
duh! I think it would work indeed. Will give this a shot.

**Comment by lucgagan** [comment]
How do I distinguish in `onRequest` whether the request is trying to upgrade or not?
