### ISSUE TITLE
Example of usage with WebSockets?

### ISSUE THREAD

**Issue by RIP21** [fastify/fastify-websocket#223]
Hey I would like to use this as a proxy for local development and I'm not sure how to configure this proxy so WebSocket proxying is working.

It's not clear how to do that from README.md

Thanks

**Comment by RIP21** [comment]
@climba03003 obviously but there is a whole section in this library that actually mentions this library.
https://github.com/fastify/fastify-http-proxy#websocket
So I thought there is a good example of how it works.

**Comment by climba03003** [comment]
Proxy would be a dedicated usage for each developer. I don't think it is good to provide an example which would not cover all case and the maintain of this example would be a hard job.

You can scan through how to use `ws` inside `@fastify/http-proxy` [source code](https://github.com/fastify/fastify-http-proxy/blob/master/index.js#L39-L59).
