### ISSUE TITLE
websocket status is always CONNECTING

### ISSUE THREAD

**Issue by herosql** [fastify/fastify-websocket#229]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

7.1.1

### Node.js version

16.13.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

websocket status is always CONNECTING

### Steps to Reproduce

init project
```shell
npm init -y
yarn add fastify
yarn add @fastify/websocket
```
write code
```javascript
const fastify = require('fastify')();
fastify.register(require('@fastify/websocket'));
 fastify.get('/hello', (request, reply) => {
     reply.send({
         message: 'Hello Fastify'
     });
 });

 fastify.get('/hello-ws', { websocket: true }, (connection, req) => {
     connection.socket.on('message', message => {
         connection.socket.send('Hello Fastify WebSockets');
     });
 });

 fastify.listen({ port: 3000 }, (err, address) => {
     if(err) {
         console.error(err);
         process.exit(1);     }
     console.log(`Server listening at: ${address}`);
 });
```
connect test
![Screenshot from 2022-11-07 18-20-38](https://user-images.githubusercontent.com/39084622/200286472-1dcb76e0-3fdc-483f-b0de-82599fbd3c5e.png)

### Expected Behavior

 websocket status is Connected

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by herosql** [comment]
Sorry, there is something wrong with my usage

**Comment by kodemon** [comment]
> Sorry, there is something wrong with my usage

@herosql what was wrong with your usage?
