### ISSUE TITLE
Support for routing

### ISSUE THREAD

**Issue by fox1t** [fastify/fastify-websocket#23]
Hi, I just finished implementing routing plugin for WS server. I needed it for declaring multiple handlers and a "404 error" fallback on unregistered routes.
Before publishing on npm, I was wandering if it would be a PR for this repo, instead of creating a new package.
Here is the code: https://github.com/fox1t/fastify-websocket-router

I'll delay publishing till this issue will be closed.

**Comment by Eomm** [comment]
I think it could be a nice feature to add!

> I was wandering if it would be a PR for this repo, instead of creating a new package.
This is up to you, I would be glad to help in a PR like this one 💪
I checked your repo and it is clear and simple, I would add only some more checks in input and few more tests that could be helpful

**Comment by fox1t** [comment]
I think that is better to add it in this package, so I'll go for PR. Is it OK if I port the code to TS?

**Comment by delvedor** [comment]
I would love to see that feature in this plugin :)
@mcollina what do you think?

**Comment by mcollina** [comment]
I think adding routing would definitely be fantastic, but I’m not really comfortable in porting this to ts yet.

(I’m catching up on emails, sorry for the long delay).

**Comment by fox1t** [comment]
Hi. No worries about "long delay"! :)
I see. May I ask you why are you not comfortable in porting it to TS? It is just for my personal curiosity. 
I use my [TS lib starter](https://github.com/fox1t/typescript-lib-starter) for TS projects like this, that is heavly based on Fastify's team toolchain and project setup, such as node-tap for testing and azurepipeline for CI/CD. TS is used to have typings out of the box and not in `.d` files that are more difficult to maintain.

Anyway, I think we have to options to choose from (excluding porting this to TS):
- I can port to JS what i did in [fastify-websocket-router](https://github.com/fox1t/fastify-websocket-router) and include it here.
- we can add more tests to [fastify-websocket-router](https://github.com/fox1t/fastify-websocket-router) (with @Eomm's help) and publish it as separate package.

Let me know what you think.

**Comment by mcollina** [comment]
I'm not a typescript user and I do not plan to become one. A significant chunk of the  maintainers in this do not wish to contribute to typescript projects. Converting a library to typescript for no significant gain is going to alienate our existing collaborator base.

Moreover, this module is not complex enough where converting to typescript would give any benefit at all.

---

In that module I see the problem of managing encapsulation, similar to how we manage it in Fastify.

**Comment by fox1t** [comment]
Can you elaborate "In that module I see the problem of managing encapsulation, similar to how we manage it in Fastify.", so I can try to fix them, if possible.

**Comment by mcollina** [comment]
The way `prefix` work in Fastify is not honoured in your module. In order to do so, you'll need to mingle with the router in a similar way we do in Fastify.

Essentially if I register a websocket handler in plugin with prefix `/foo/bar`, I expect it to include that in the routing logic.

**Comment by fox1t** [comment]
OK, thanks for the clarification, I appreciate it. 
I was playing with Fastify 'onRoute' hook and decided to try to implement this feature using fastify's router. I added new optional routeOptions `wss: boolean`: if true it will replace the http handler and will use the passed handler for ws connection. [here you can find the hook](https://github.com/fox1t/fastify-websocket-router/blob/using-fastify-router/src/index.ts#L25), [here fastify get route](https://github.com/fox1t/fastify-websocket-router/blob/using-fastify-router/test/index.ts#L14) and [here test with prefix](https://github.com/fox1t/fastify-websocket-router/blob/using-fastify-router/test/index.ts#L40)

It is passing all the tests, but it is just an idea. Before going on, and eventually implementing it directly here, I want to know if this could be the right direction.

**Comment by mcollina** [comment]
That's actually nice, however I see that some users might want to specify both a websocket handler and a non-websocket handler.

**Comment by fox1t** [comment]
Maybe we can add a new property on routeOptions: `wsHandler(connection, request): void`, to mimic the 'standard' `handler`one? In that case we don't need to return 404 on http request to the same route, if handler is defined.

**Comment by mcollina** [comment]
+1!

Il giorno lun 13 mag 2019 alle 17:44 Maksim Sinik <notifications@github.com>
ha scritto:

**Comment by fox1t** [comment]
If [this could work](https://github.com/fox1t/fastify-websocket-router/blob/using-fastify-router/test/index.ts#L91), I think that I will continue implementing this feature directly here, using PR to track progress. Is it OK for you?

**Comment by mcollina** [comment]
Ok for me, yes!

**Comment by fox1t** [comment]
Just opened the PR: https://github.com/fastify/fastify-websocket/pull/26

**Comment by fox1t** [comment]
I think that we need to increase the major version here, because of the https://github.com/fastify/fastify-websocket/pull/26

**Comment by mcollina** [comment]
I agree!

Il giorno ven 17 mag 2019 alle 13:47 Maksim Sinik <notifications@github.com>
ha scritto:

**Comment by fox1t** [comment]
I suppose we can close this issue.

**Comment by Eomm** [comment]
released in v0.5.0 👍
