### ISSUE TITLE
[FSTDEP014] FastifyDeprecation: You are trying to set/access the default route.

### ISSUE THREAD

**Issue by evshiron** [fastify/fastify-websocket#236]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I start a fastify project with websocket today and receive the following warning:

```
[FSTDEP014] FastifyDeprecation: You are trying to set/access the default route. This property is deprecated. Please, use setNotFoundHandler if you want to custom a 404 handler or the wildcard (*) to match all routes.
```

The relevant lines of code are:
* https://github.com/fastify/fastify/blob/main/lib/route.js#L91
* https://github.com/fastify/fastify-websocket/blob/master/index.js#L185

Which might require some refactoring to make it disappear.

**Comment by tobbe-r** [comment]
+1 Experiencing the exact same issue

**Comment by RafaelGSS** [comment]
That's expected. See https://github.com/fastify/fastify/pull/4480

**Comment by jsumners** [comment]
Please read the notice and follow the instructions therein.

**Comment by Uzlopak** [comment]
Probably open an issue in fastify-websocket to take care of the Deprecation warning and tag it with good first issue

**Comment by MarianoFacundoArch** [comment]
We should fix this to use new methods?

**Comment by jsumners** [comment]
> We should fix this to use new methods?

Yes.

**Comment by evshiron** [comment]
Thanks for the replies and just to confirm, if I get it right, because the call to deprecated methods happens in [fastify/fastify-websocket](https://github.com/fastify/fastify-websocket) (this repo), we (actually you, the maintainers) will update it someday, right?

**Comment by jsumners** [comment]
Yes, this module needs to be updated. It is the community's responsibility to keep the things they use updated. This software is provided as-is.

**Comment by climba03003** [comment]
Do we need to replace `defaut route` in this case? I see we drop [`hijacking error handling`](https://github.com/fastify/fastify-websocket/commit/1848dfe88fbb671b858a3aa483e46da9dfcd8bc0) already, maybe just drop `default route` in this case.
cc @airhorns

**Comment by mcollina** [comment]
I would need to see what tests breaks. Ideally, that's what we would do.

**Comment by xtremespb** [comment]
What about replacing the default route logic by prehandler?

```javascript
fastify.addHook("preHandler", (request, reply, done) => {
    if (request[kWs]) {
        handleUpgrade(request, (connection) => {
            noHandle.call(fastify, connection, request);
        });
    }
    done();
});
```

**Comment by climba03003** [comment]
> What about replacing the default route logic by prehandler?

No, they are not identical. `pre-handler` will not run for the route that is not exist.

Removal of `default route` means when the route is not explicitly defined. No upgrade will be allowed.
Whereas, currently it upgraded and close afterward.

**Comment by mcollina** [comment]
Would that change the behavior significantly?

**Comment by climba03003** [comment]
> Would that change the behavior significantly?

I believe the impact would be minimal.

Current
```mermaid
sequenceDiagram
    Broswer->>+Server: Initial Connection with WebScoket
    Server->>-Broswer: 101 Switch Protocol
    Broswer->>+Server: Connection Establish
    Server->>-Broswer: Immediate Close
    Broswer->>+Broswer: Handle by .onclose
```

After removal of `default route`
```mermaid
sequenceDiagram
    Broswer->>+Server: Initial Connection with WebScoket
    Server->>-Broswer: 404 Not Found
    Broswer->>+Broswer: Handle by .onerror or .onclose
```

**Comment by mcollina** [comment]
Seems even better. My guess is that was a relic of some past code.
