### ISSUE TITLE
Fastify deprecates getDefaultRoute/setDefaultRoute

### ISSUE THREAD

**Issue by marcolanaro** [fastify/fastify-websocket#239]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently, servers using this library logs this kind of errors: `[FSTDEP014] FastifyDeprecation: You are trying to set/access the default route. This property is deprecated. Please, use setNotFoundHandler if you want to custom a 404 handler or the wildcard (*) to match all routes.`.

This is because of this deprecation [https://github.com/fastify/fastify/commit/fc81c707b819894bd84a903e5bbd23ec121e5a7b](https://github.com/fastify/fastify/commit/fc81c707b819894bd84a903e5bbd23ec121e5a7b).

The issue to help tracking dependency adoption.

**Comment by Uzlopak** [comment]
Ensure that you use the latest version of @fastfy/websocket as this was patched in version 7.1.2
