### ISSUE TITLE
req.query is undefined

### ISSUE THREAD

**Issue by Worldwidebrine** [fastify/fastify-websocket#251]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Plugin version

7.2.0

### Node.js version

v18.16.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10.0.22621

### Description

`req.query` is undefined.
`req.request.query` is the query but TypeScript thinks `req.request` doesn't exist.

### Steps to Reproduce

```js
fastify.get("*", {...}, (conn, req) => {
    console.log(req.query);
    console.log(req.request.query);
});
```
```
undefined
Empty <[Object: null prototype] {}> { test: 'abc' }
```

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Worldwidebrine** [comment]
Oh. I forgot to await fastify.register(websocket)
