### ISSUE TITLE
👋 I would like to contribute to fastify/fastify-websocket

### ISSUE THREAD

**Issue by synapse** [fastify/fastify-websocket#292]
Hi there,

regarding the Update modules for v5 https://github.com/fastify/fastify/issues/5116, I would like to help. Could you please create the next branch?

Thank you

**Comment by Uzlopak** [comment]
Instead of opening multiple issues with the same text, create new Prs pointing to master/main and write to provide a next branch. And then when created next you can change the target of your pr to next.

**Comment by Uzlopak** [comment]
Created next.

**Comment by jsumners** [comment]
> Instead of opening multiple issues with the same text, create new Prs pointing to master/main and write to provide a next branch. And then when created next you can change the target of your pr to next.

Please read the issue that was linked.

**Comment by Uzlopak** [comment]
@jsumners you are right. my fault
