### ISSUE TITLE
The close event callback function is not triggered.

### ISSUE THREAD

**Issue by michael19900101** [fastify/fastify-websocket#297]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

10.0.1

### Node.js version

20.10.6

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

mac os 13.3

### Description

When the Android app, acting as a WebSocket client, loses its network connection, the close event callback function is not triggered on the Fastify server side when using the fastify-websocket plugin.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

(Please provide the reproduction using Node.js)
