### ISSUE TITLE
Socket.io plugin?

### ISSUE THREAD

**Issue by cagataycali** [fastify/fastify-websocket#3]
Any idea for socket.io?

**Comment by mcollina** [comment]
I do not think we need socket.io in 2017. Websockets are supported kind-of everywhere.

**Comment by mattbrunetti** [comment]
Socket.io adds more than just fall-back to other transports (i.e. long polling). First things that spring to mind are: automatic re-connection, and namespacing events to "rooms" (not to mention events themselves). And it has a good & stable API for these things (and more) which developers are familiar with now. 

I would prefer a socket.io plugin over this bare bones websocket plugin, where I'd have to add that functionality and it would end up being a unique (non-standard API).

I just found out about this project (*very* exciting btw) and after I get a bit more into it (won't take long I'm sure) I'll probably look into creating a socket.io plugin, and getting it listed with the [Community plugins](https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md#community)

**Comment by mcollina** [comment]
@mattbrunetti go ahead and do it :).
