### ISSUE TITLE
Drop websocket-stream and just use ws

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-websocket#32]
The [ws](http://npm.im/ws) added support for native node streams. We can drop websocket-stream and just use that.

https://www.npmjs.com/package/ws#use-the-nodejs-streams-api

**Comment by Eomm** [comment]
I have started some coding to check it.

Do you know why in the test has been used `connection.socket`?
It is a matter only of streaming-apis and eventemitter-apis?

**Comment by mcollina** [comment]
no clue. Link?

Il giorno ven 23 ago 2019 alle 22:23 Manuel Spigolon <
notifications@github.com> ha scritto:

**Comment by Eomm** [comment]
This is one example:

https://github.com/fastify/fastify-websocket/blob/68f2b4c9d1979b97e6eb5017b83dc9bd3150cba4/test/router.js#L119-L123

**Comment by mcollina** [comment]
Did that on(‘message’) block run right now? I does not seem so. Also, The
client is connecting to a different URL.

Il giorno sab 24 ago 2019 alle 09:25 Manuel Spigolon <
notifications@github.com> ha scritto:

**Comment by fox1t** [comment]
Hi. That test is correct since it test `Should close on unregistered path`. Calling it on unregistered path (`/`) just closes the connection. That's the point of the test.
@Eomm I really don't understand you initial question, can you elaborate?

**Comment by jenokizm** [comment]
What is the difference with https://github.com/gj/fastify-ws ?

**Comment by mcollina** [comment]
> What is the difference with https://github.com/gj/fastify-ws ?

This library has many more features.

**Comment by jenokizm** [comment]
> This library has many more features.

OK. what about performance? Do you recommend this one?

**Comment by Eomm** [comment]
Closing since this issue has been completed in https://github.com/fastify/fastify-websocket/pull/38
