### ISSUE TITLE
Add an option to not wrap the websocket in a stream

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-websocket#40]
## 🚀 Feature Proposal

Currently we wrap every websocket connection in a Node Stream, however it might be handy to _not_ do that in certain cases. We could add an option to avoid that.

### Example

```js
const fastify = require('fastify')()

fastify.register(require('fastify-websocket'), {
  handle,
  stream: false
})
```

**Comment by mcollina** [comment]
cc @SkeLLLa

**Comment by SkeLLLa** [comment]
@mcollina so when `stream: false` in handler function we'll receive just plain object:
```
{ 
  socket
}
```
instead of duplex stream, correct?

**Comment by mcollina** [comment]
I would just receive `socket`.

**Comment by theodesp** [comment]
Congrats for this great project. Is it OK If I can tackle this?

So looking at the code, I should just check if the stream parameter is set here and just return the connection object:

https://github.com/fastify/fastify-websocket/blob/master/index.js#L66

Then update the Type definitions to match the handler type. Is that OK?

**Comment by SkeLLLa** [comment]
@theodesp yes, you're right.

**Comment by theodesp** [comment]
@SkeLLLa PR added https://github.com/fastify/fastify-websocket/pull/48. Open for improvements/changes.

**Comment by KrishnaPG** [comment]
Wondering about the status of this. The PR seems done but not merged yet. Would be great, if it is merged, so we can start using it.
