### ISSUE TITLE
How can I broadcast to all connected sockets?

### ISSUE THREAD

**Issue by eliecer2000** [fastify/fastify-websocket#42]
I have no problems with the connection, all clients connect without problem. My question is how can I send a message to everyone at the same time since I have tried the examples of the 'ws' library but I have not succeeded. Someone has an example code, here I leave part of my code on the server.

```
  fastify.route({
    method: 'GET',
    url: '/',
    handler: (req, reply) => {
      reply.send({ ruta: 'OK' })
    },
    wsHandler: (conn, req, params) => {
      conn.setEncoding('utf8')
      conn.on('data', chunk => {
        console.log(chunk)
        conn.socket.send('message OK')
      })
    }
  })
```

**Comment by mcollina** [comment]
You'll need to use some sort of pubsub support, check out https://github.com/mcollina/mqemitter

**Comment by eAmin** [comment]
Why would we should use other dependencies?
Can we use or add this ability to this library to broadcast clients:
```javascript
  wss.clients.forEach(.......) 
```

**Comment by rurico** [comment]
```javascript
fastify.websocketServer.clients.forEach(function each(client) {
    if (client.readyState === 1) {
      client.send(  .......  )
    }
})
```

**Comment by Eomm** [comment]
> Why would we should use other dependencies?

@eAmin In a distributed environment a `forEach` solution would send messages only to the clients connected to a single server; Using a pub/sub architecture let you avoid this issue.

Anyway, we are open to PR in order to improve docs or add new features if you would like to contribute 💪

**Comment by rizalashidiq97** [comment]
can we use redis for this ?

**Comment by rizalashidiq97** [comment]
how do we integrate this then ?

**Comment by mcollina** [comment]
https://github.com/mcollina/fastify-gql includes an example of that implementation/integration. I'm going to close as this is out of scope of this module.
