### ISSUE TITLE
Is websocketServer implemented for TypeScript?

### ISSUE THREAD

**Issue by karianpour** [fastify/fastify-websocket#50]
Using typescript, as I wanted to access `websocketServer` the type says that it is not defined. I am wondering If the type is defined.

This gives error:
`fastify.websocketServer.clients`

So I opt to `any` which works cause it is there.
`(fastifyServer as any).websocketServer.clients`

@fox1t as I saw that you implemented the types, can you help me on the matter, please?

**Comment by fox1t** [comment]
Of course I can! Thanks for pointing this out. Can you please make a reproduction repository here on GitHub, so I can clone it and look into it using your same env. 

Thanks again!

**Comment by GuskiS** [comment]
I think `websocketServer` is missing from https://github.com/fastify/fastify-websocket/blob/master/index.d.ts#L20 interface. It should contain `websocketServer: WebSocket`?

**Comment by fox1t** [comment]
> I think `websocketServer` is missing from https://github.com/fastify/fastify-websocket/blob/master/index.d.ts#L20 interface. It should contain `websocketServer: WebSocket.Server`?

I think you are right! Would you mind to make a PR fixing it?

**Comment by GuskiS** [comment]
I opened PR from web github, didn't run it locally tho.
