### ISSUE TITLE
TypeScript Typing for second param (request) is wrong

### ISSUE THREAD

**Issue by patarapolw** [fastify/fastify-websocket#60]
## 🐛 Bug Report

It seems not to be `FastifyRequest`

- It does not have `req.params`. (I now know it is in the third (3rd) params)
- `req.log` is undefined, not Pino Logger. I have to import Pino (and install both `pino` and `@types/pino`) directly to activate logging.

## Expected behavior

- Please append logger to `req`.
- Do not use Typing for `FastifyRequest` if it does not have `params` nor `log`.

## Your Environment

- *node version*: 10, 12 (tested with both)
- *fastify version*:

```json
    "fastify": "^2.14.1",
    "fastify-cors": "^3.0.3",
    "fastify-file-upload": "^2.0.1",
    "fastify-helmet": "^3.0.2",
    "fastify-oas": "^2.7.0",
    "fastify-static": "^2.7.0",
    "fastify-websocket": "^1.1.2",
```

- *os*: macOS Catalina

**Comment by mcollina** [comment]
Would you mind to send a PR? The 1.x branch is in https://github.com/fastify/fastify-websocket/commits/v1.x.

**Comment by airhorns** [comment]
This is fixed now!
