### ISSUE TITLE
ws not working with empty get path when using prefix

### ISSUE THREAD

**Issue by MomenNano** [fastify/fastify-websocket#61]
## 🐛 Bug Report

when I register api module and give it a prefix option and then in the module file I can't set get route without any additional path name ` fastify.get('/',  { websocket: true }, <function>)`
and it gives me the error 
> AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/api/'

it works when I add something to get path like `fastify.get('/hi', { websocket: true }, <function>)`
_app.js_
```js
fastify.register(require('fastify-websocket'))

fastify.register(require('./api), { prefix: '/api' }
```

_api.js_
```js
fastify.get('/', { websocket: true }, <function>)
````
## Expected behavior

It should work in websocket. like it works fine without websocket (regular get '/' path)

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Windows

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by MomenNano** [comment]
I fixed it and I'll send a pull request
