### ISSUE TITLE
Client loses the connection when the total amount of data sent exceeds 16384 bytes

### ISSUE THREAD

**Issue by asyncnomi** [fastify/fastify-websocket#74]
## 🐛 Bug Report

When a client send more than a total of 16384 bytes to the server he is no longer able to send, but it can still receive data from the server. It's not necessary to send the 16384 bytes or more in a single message, this can be four times 5000 bytes for example. I also observed that the message that will exceed the 16384 bytes will be fully send, In the above example the fouth message of 5000 bytes will be entirely send but the next one won't.

## To Reproduce

To Reproduce, just execute the code below

```js
/* /// SERVER /// */

'use strict'

const fastify = require('fastify')({logger: true})

fastify.register(require('fastify-websocket'), {
  handle,
  options: {
    maxPayload: 1048576, // 1Mio
    path: '/', 
  }
})

function handle (conn) {
  conn.socket.on('message', (msg) => {
    console.log(msg)
    conn.socket.send(msg)
  })
}

const start = async () => {
  try {
    await fastify.listen(3000, "0.0.0.0")
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()

/* /// CLIENT /// */

var socket = new WebSocket("ws://<ip adress>:3000");
socket.addEventListener('message', (msg) => {
	console.log(msg);
})

var data = "a".repeat(16384);
socket.send(data); // This one will be see in the server console and the client will receive the "echo"
socket.send(data); // This one won't be see in the server and client console
```

## Your Environment

- *node version*: 10.21.0
- *fastify version*: >=2.0.0
- *os*: Linux (Raspbian)

**Comment by Eomm** [comment]
I have 3 solutions for you!

The `conn` parameter is a `WebSocketStream` that is [paused after each message](https://github.com/websockets/ws/blob/88d0345997ea14b262519c7d5b5baaf6f9d78035/lib/stream.js#L73)

So you need to:

1) resume the connection

```
  conn.socket.on('message', (msg) => {
    console.log(msg.length)
    conn.socket.send(msg)
    conn.resume()
  })
```

2) use the `data` event of the stream:

```
  conn.on('data', (msg) => {
    console.log('data', msg.length)
    conn.socket.send(msg)
  })
```

or 3) just use the stream pipe (through TrasformationStream or something else):

```
conn.pipe(conn)
```

Moreover, in the client you should wait for the open callback before sending:

```
    socket.addEventListener('open', function (event) {
      console.log(socket.bufferedAmount);
      socket.send("X".repeat(16384));
      console.log(socket.bufferedAmount);
      socket.send("O".repeat(16384));
      console.log(socket.bufferedAmount);
    });
```

**Comment by asyncnomi** [comment]
Thank you so much !
