### ISSUE TITLE
Socket stops accepting messages

### ISSUE THREAD

**Issue by cope** [fastify/fastify-websocket#77]
I'm kind of loosing my mind over this...

## 🐛 Bug Report

Server-side socket stops accepting messages, even though the connection remains open and it is still able to send messages.

## To Reproduce

See https://github.com/cope/wtfws for an extremely detail description and ability to clone and repro the issue.

## Expected behavior

Server-side socket to KEEP accepting messages.

## Your Environment

- *node version*: 12.18.3
- *fastify version*: >=3.4.1
- *os*: Windows
- *any other relevant information*: see https://github.com/cope/wtfws

**Comment by mcollina** [comment]
For some reason you need:

```
function handleConnection(connection) {
	const {socket} = connection;
        connection.resume(); // <--- this is needed.
	handleSocket(socket);
}
```

You have found a really nice bug! I did not know about it - I think we can automatically handle this in the module.

**Comment by cope** [comment]
Oh come on, it can't be THAT easy... took me forever to just point to it properly... 😭 

Jokes aside, **THANKS!** 😃

**Comment by cope** [comment]
So glad I don't have to revert to express 😉

**Comment by mcollina** [comment]
The solution was in your example tbh. It was super easy to catch because of the repro. I also know all the stack :).
