### ISSUE TITLE
Websocket stuck after receiving around ~16 kb of data from client

### ISSUE THREAD

**Issue by zmeyc** [fastify/fastify-websocket#80]
## 🐛 Bug Report

After client sends ~100 messages of ~160 bytes each to websocket, `connection.socket.on('message')` is no longer being triggered.

It seems to be size-dependent, I can send thousands of very short (a few bytes) messages, but only around 100 lines of 160 bytes.

## To Reproduce

In new dir:

```
yarn init
yarn add fastify fastify-websocket
```

Create `server.js`:

```
'use strict'

const fastify = require('fastify')()

fastify.register(require('fastify-websocket'))

fastify.get('/', { websocket: true }, (connection, req) => {
  connection.socket.on('message', message => {
    // message === 'hi from client'
    connection.socket.send('hi from server')
  })
})

fastify.listen(5000, err => {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
```

Run `node server.js`

In another window, run:
```
wscat --show-ping-pong -c "ws://localhost:5000"
```

Create a file with ~150 lines of 160 bytes each. Copy-paste contents into wscat.

The server will stop responding.

## Expected behavior

Should keep returning responses.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac, Linux

**Comment by mcollina** [comment]
Which version are you using? We fixed this in https://github.com/fastify/fastify-websocket/pull/78.

**Comment by zmeyc** [comment]
@mcollina latest one, 2.0.9

**Comment by zmeyc** [comment]
I checked that pure ws@7.3.1 with default settings works stably (without calling connection.resume()):

```
import WebSocket from 'ws'
const webSocketServer = new WebSocket.Server({ port: websocketPort })
webSocketServer.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message)
    ws.send(`got ${message}`)
  })
  ws.send('connected')
})
```
