### ISSUE TITLE
Bump find-my-way from 3.0.4 to 3.0.5

### ISSUE THREAD

**Issue by tylercraft** [fastify/fastify-websocket#92]
This project uses `find-my-way` and is pinned to `3.0.4`. Can you please bump it to `3.0.5` (which is what it is in the main fastify project).

This is currently causing dependency alerts in repo's that use this project due to this:
https://github.com/advisories/GHSA-jgrh-5m3h-9c5f

**Comment by jsumners** [comment]
It is not "pinned" -- https://github.com/fastify/fastify-websocket/blob/ba6d79c8613290e5e66bbf62f69c0097c7050a0d/package.json#L42

https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

`^3.0.4` indicates the _minimum_ supported version.

**Comment by tylercraft** [comment]
Sorry, misread. That said, the ask is the same, that the version number gets bumped.

**Comment by jsumners** [comment]
Sure, a PR to do it would be welcome. But I fail to understand how this is an issue since an install should cover it.

**Comment by tylercraft** [comment]
I'd be happy to create a PR, in fact I've already created a local branch with a commit, but don't have permissions to push. 

Regarding being an `issue`, I wasn't sure the best way to submit it. The instructions weren't clear. It's not a feature. It's not a 'regression'. It's already a public vulnerability, so going down that path seemed overkill. In the future I'll just bump it, run the tests and submit the PR.

**Comment by jsumners** [comment]
> I'd be happy to create a PR, in fact I've already created a local branch with a commit, but don't have permissions to push.

See https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by tylercraft** [comment]
Thanks, closing this out as PR is created: https://github.com/fastify/fastify-websocket/pull/93
