### ISSUE TITLE
Fastify 3.10 breaks prefixed plugins

### ISSUE THREAD

**Issue by Skn0tt** [fastify/fastify-websocket#97]
## 🐛 Bug Report

Fastify 3.10, together with the use of prefixes, breaks `fastify-websocket`.

```ts
fastify.register(
  (fastify, opts, done) => {
    fastify.get("/", { websocket: true }, (connection, req) => {
      connection.socket.send("This works");
    });

    done();
  },
  { prefix: "/activity" }
);
```

## To Reproduce

- Clone https://github.com/Skn0tt/fastify-websocket-3.10-repro
- Run `index.js`
- Connect to `ws://localhost:3000/activity`

## Your Environment

- *node version*: 15.3
- *fastify version*: >=3.10
- *os*: Mac

## Some ideas as to what may be causing this

Prior to 3.10, this line was called twice per route:

https://github.com/fastify/fastify-websocket/blob/99c94a003da2353c1f482301027166e64e743582/index.js#L36

That's why this lines makes sure to ignore one of them:

https://github.com/fastify/fastify-websocket/blob/99c94a003da2353c1f482301027166e64e743582/index.js#L42

Now with 3.10, the `onRoute` is called only once, and _all_ of the routes are effectively ignored.

> originally encountered in https://github.com/quirrel-dev/quirrel/issues/49

**Comment by mcollina** [comment]
I agree with your analysis! Would you like to send a PR to fix this module?

**Comment by mcollina** [comment]
Please check out https://github.com/fastify/fastify-websocket/pull/98, it should fix the problem.
