### ISSUE TITLE
Global Handler parameter problem?

### ISSUE THREAD

**Issue by caryhgq** [fastify/fastify-websocket#99]
## 🐛 Bug Report

The second parameter of the Global Handler should be ServerRequest instead of ServerResponse.

## To Reproduce

```js
app.register(require("fastify-websocket"), {
  handle: (ws,req) => {
    console.log(req);  // This should be Request, not Response
    wsHandle(ws);
  },
  options: {
    maxPayload: 1048576,
    path: "/websocket",
  },
});
```

![image](https://user-images.githubusercontent.com/6456736/105473158-be939880-5cd7-11eb-84d8-2d5a551846e7.png)

![image](https://user-images.githubusercontent.com/6456736/105473205-c8b59700-5cd7-11eb-85d9-b6661378f633.png)

## Expected behavior

The second parameter of the Global Handler is ServerRequest

```
app.register(require("fastify-websocket"), {
  handle: (ws,req) => {
    console.log(req);  // Here is the Request
    wsHandle(ws);
  },
  options: {
    maxPayload: 1048576,
    path: "/websocket",
  },
});

```
https://github.com/fastify/fastify-websocket/blob/c276f6dbc8da0da3e4a87bd7b81ff8b237c5156f/index.js#L83

## Your Environment

- *node version*: v14.15.4
- *fastify version*: >=3.10.1
- *os*: Mac, Windows, Linux
- *fastify-websocket version*:>=2.1.0

**Comment by fox1t** [comment]
Hi @caryhgq. You can check the handle signature here: https://github.com/fastify/fastify-websocket/blob/c276f6dbc8da0da3e4a87bd7b81ff8b237c5156f/index.js#L86

As you can see it has only 2 parameters. This is different from  the `wsHanlder` that as 3.

**Comment by caryhgq** [comment]
The new release of V3.0.0 has fixed the problem
